spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dsp.ext.gpmn.net:9209/retail_platform
    username: root
    password: 123456a@A
#server:
#  servlet:
#    context-path: /auth