spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.230.191.178:9306/retail_platform
    username: root
    password: 123456a@A
  jpa:
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: 10.230.191.178

#server:
#  servlet:
#    context-path: /auth

#logging:
#  level:
#    net:
#      ttddyy:
#        dsproxy:
#          listener: debug
