spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_URL:10.30.174.212:8771/retail_platform}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456a@A}
  jpa:
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:10.230.191.178}
      port: ${REDIS_PORT:9379}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:10.230.191.178:9092}

info:
  minio:
    url: ${MINIO_URL:10.30.174.212}
    port: ${MINIO_PORT:8773}
    username: ${MINIO_USERNAME:admin}
    password: ${MINIO_PASSWORD:123456a@A}
    secure: false
    file-size: 104857600
  storage-service: ${STORAGE_SERVICE:10.230.191.178:8102}

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

server:
  port: 8100
