spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.30.174.212:8771/retail_platform
    username: root
    password: 123456a@A
  jpa:
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: 10.230.191.178
      port: 9379
  kafka:
    bootstrap-servers: 10.230.191.178:9092

info:
  minio:
    url: 10.30.174.212
    port: 8773
    secure: false
    username: admin
    password: 123456a@A
    fileSize: 104857600

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

server:
  port: 8100
